[package]
name = "rmvm-sidecar"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "rmvm-grpc-server"
path = "src/main.rs"

[dependencies]
rmvm-grpc.workspace = true
tokio.workspace = true
tonic = "0.14.5"
